default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username:  <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%=  ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default
  # database: desafio_ninja_test

production:
  <<: *default
  # database: desafio_ninja_production
  # username: desafio_ninja
  # password: <%= ENV["DESAFIO_NINJA_DATABASE_PASSWORD"] %>